### ISSUE TITLE
crash when opening chat

### ISSUE THREAD

**Issue by supremebloxboy** [powware/pd2-chat-translator#12]
update 240 broke this mod. A crash will occur when opening chat. there is a fix however and that's by also having a hud mod installed like VanillaHUD/VoidUI. but this is still an issue on default hud. I did fix it by updating some hudchat functions to updated versions. I submitted a pull request.

**Comment by powware** [comment]
can you check if the latest version fixed the issue

**Comment by supremebloxboy** [comment]
yup everything works with the latest version. i tested with default/void/vanilla. wolf still crashes when opening chat but thats not on your end. this can be fixed by replacing wolfhuds HUDChat.lua with the one from the Custom Chat Standalone mod modworkshop.net/mod/32297. so thats not an issue on your end. its just wolf hud being outdated. i closed my pull request.
